version: "3"

services:

  
  # pushgateway:
  #   image: "prom/pushgateway:v1.6.2"
  #   ports:
  #     - 9091:9091
  #   volumes:
  #     - ./config/web-config/web-config.yaml:/etc/prometheus/web-config.yaml:ro
  #   command:
  #     - "--web.config.file=/etc/prometheus/web-config.yaml"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     update_config:
  #       order: start-first
  #     resources:
  #       limits:
  #         memory: 512M
          
  
  promtail:
    image: "grafana/promtail:2.9.0"
    volumes:
      # touch /mnt/common_volume/swarm/grafana/config/promtail.yaml;
      # mkdir -p /mnt/common_volume/grafana/promtail-data;
      - ./client-config/promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
      - ./data/promtail/promtail-data:/var/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    environment:
      HOST_HOSTNAME: "{{Hostname}}"
    command:
      - "--config.file=/etc/promtail/promtail.yaml"
      - "--config.expand-env=true"
    deploy:
      mode: global
      update_config:
        order: stop-first
      resources:
        limits:
          memory: 512M


