auth_enabled: false

server:
  http_listen_port: 3100

# common:
#   path_prefix: /loki
#   storage:
#     s3:
#       s3: https://log-bucket-d021650d.fra1.digitaloceanspaces.com
#       bucketnames: log-bucket-d021650d
#       region: fra1
#       access_key_id: "DO00NH8H2NMM9XDLJBWU"
#       secret_access_key: "P7r8niFw4xXtOOKOPCT2ICmy6EzWY7aVpBp+WS7lGyw"
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: inmemory

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    # cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: s3
  aws:
    s3: s3://DO00NH8H2NMM9XDLJBWU:P7r8niFw4xXtOOKOPCT2ICmy6EzWY7aVpBp+WS7lGyw@fra1
    bucketnames: log-bucket-d021650d

schema_config:
  configs:
    - from: 2020-07-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 7d # days to delete old logs, you can change
  max_query_lookback: 7d # days to delete old logs, you can change

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false

chunk_store_config:
  max_look_back_period: 7d # days to delete old logs, you can change

compactor:
  working_directory: /loki/retention
  shared_store: filesystem
  compaction_interval: 15m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

querier:
  query_ingesters_within: 2h # avoid https://github.com/grafana/loki/issues/6043
