# This is a complete configuration to deploy Loki backed by a s3-Comaptible API
# like MinIO for storage. Loki components will use memberlist ring to shard and
# the index will be shipped to storage via boltdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  chunk_idle_period: 3m
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    dir: /loki/wal

# common:
#   ring:
#     instance_addr: 127.0.0.1
#     kvstore:
#       store: memberlist
#   replication_factor: 1
#   path_prefix: /loki # Update this accordingly, data will be stored here.

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 360h

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3
  aws:
    bucketnames: loki
    endpoint: https://log-bucket-d021650d.fra1.digitaloceanspaces.com
    region: fra1
    access_key_id: DO0028JUEV9UAU6YB7LB
    secret_access_key: xGCx6XdGVcD2sPf02XkW4/ICOayMA4XVGQsif9KrfTk
    s3forcepathstyle: true

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 360h

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 1m
